[versions]

gradle-plugin = "7.2.1"

kotlin = "1.7.10"

android-build-tools = "30.0.3"
android-sdk-compile = "31"
android-sdk-min = "29"
android-sdk-target = "31"

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle.plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
